### ISSUE TITLE
JDK 11 compatibility

### ISSUE THREAD

**Issue by Barachia** [hmi-utwente/Flipper-2.0#11]
There's a difference between the JDK 8 and JDK 11, in which Flipper is unable to parse arguments for methods, functions and constructors other than type Strings.

**Comment by Barachia** [comment]
Some additional information on this bug with an example. I'm running JDK 11.0.1, using the Nashorn scriptengine, with the `Flipper2Count.xml` example template. When running the `Main` class, I bump into an argument type mismatch.

`JavaCall failed:JavaEffect:executeCall: JavaEffect[name=f, className=hmi.flipper2.example.Dynamic]
Arguments=[java.lang.Integer ]
!TemplateFile: Test Tid: 1 Tname: 1
!Caught Exception: java.lang.IllegalArgumentException: argument type mismatch
!Stack: 
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hmi.flipper2.effect.JavaEffect.executeCall(JavaEffect.java:157)
	at hmi.flipper2.effect.JavaEffect.doIt(JavaEffect.java:127)
	at hmi.flipper2.effect.EffectList.doIt(EffectList.java:71)
	at hmi.flipper2.Template.executeSelectedEffects(Template.java:243)
	at hmi.flipper2.Template.checkPreconditions(Template.java:233)
	at hmi.flipper2.TemplateController.checkPreconditions(TemplateController.java:357)
	at hmi.flipper2.TemplateController.checkTemplates(TemplateController.java:307)
	at hmi.flipper2.TemplateController.checkTemplates(TemplateController.java:352)
	at hmi.flipper2.Main.main(Main.java:43)
`

**Comment by Barachia** [comment]
In the [experimental ](https://github.com/hmi-utwente/Flipper-2.0/tree/experimental)branch, I've put a version of Flipper that works with JDK 11 with a workaround. It seems that the way for example this JSON String` "{ "value" = 1 }" `, it is parsed as a `Double `in JDK 8 and parsed as an `Integer `in JDK 11.

However, it's recommended to use the Flipper on the master branch. Then if you have to run JDK 11, make sure that all `Doubles `in your information state are defined of the format `x.x` (e.g. 1.0). If you run it on JDK 8, then they can be of format `x` (e.g. 1).

**Comment by Barachia** [comment]
Closing this, as it is more an issue of the JDK then of Flipper. Will add a note in the documentation.

**Comment by Barachia** [comment]
Closing this, as it is more an issue of the JDK then of Flipper. Will add a note in the documentation.
