### ISSUE TITLE
TemplateController with a database connection causes NullPointerException when using templates with databases.

### ISSUE THREAD

**Issue by Barachia** [hmi-utwente/Flipper-2.0#9]
When loading templates with a database connection, there is a NullPointerException.

```
Exception in thread "main" java.lang.NullPointerException
	at hmi.flipper2.Template.handle_effect(Template.java:116)
	at hmi.flipper2.TemplateFile.handle_database(TemplateFile.java:74)
	at hmi.flipper2.TemplateFile.handle_section(TemplateFile.java:43)
	at hmi.flipper2.TemplateFile.<init>(TemplateFile.java:34)
	at hmi.flipper2.TemplateController.addTemplateFile(TemplateController.java:209)
	at hmi.flipper2.Main.main(Main.java:39)
```

**Comment by janflokstra** [comment]
Fixed! Was cause by changes because of the new debugger!
